# docker-compose.yml
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8000"
    env_file:
      - .env  # Load environment variables from .env
    volumes:
      - .:/app  # Optional, for development